UniversitySite/University/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name= 'University'
urlpatterns = [
    #Include default auth urls
    path('', views.homepage,name="homepage"),
    path('login', views.login,name="login"),
    path('signup', views.signUp,name="signup"),
    path('menu',views.menu,name="menu"),
    path('course_add',views.course_add,name='course_add'),
    path('course_drop',views.course_drop,name='course_drop'),
    path('course_registration',views.course_registration,name='course_registration'),
    path('personal_information',views.personal_information,name='personal_information'),
    path('results',views.results,name='results'),
    path('student_registration',views.student_registration,name='student_registration'),
    
]

UniversitySite/UniversitySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('University.urls',namespace="University")),
    
]

UniversitySite/University/models.py
from distutils.archive_util import make_zipfile
from operator import mod
from pickle import FALSE
from statistics import mode
from django.db import models
from django.forms import model_to_dict
from django.contrib.auth.models import User

# Create your models here.

class OfferedCourse(models.Model):
    id=models.CharField(max_length=50,primary_key=True,null=False,blank=False,verbose_name="Course ID")
    name=models.CharField(max_length=100,null=False,blank=False,verbose_name="Course Name")
    description=models.CharField(max_length=150,null=False,blank=True,verbose_name="Description")
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

class StudentList(models.Model):
    id=models.CharField(max_length=20,primary_key=True,null=False,blank=FALSE,verbose_name="Student Id")
    fullname=models.CharField(max_length=50,null=False,verbose_name="Full Name")
    email=models.CharField(max_length=50,null=False,verbose_name="Email")
    
#Unused
class Grade(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text

class Grade(models.Model):
    course_id=models.CharField(max_length=20,null=False,blank=FALSE,verbose_name="Course Id")
    result=models.CharField(max_length=50,null=False,verbose_name="Result")
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

UniversitySite/University/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User,auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.core import serializers

from .models import OfferedCourse, Grade

from . import courseadd
from .import studentRegistration


# Create your views here.
def homepage(request):
    return render(request,"homepage.html")

def login(request):
    if request.method=='POST':
        username=request.POST['id']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('University:menu')
        else:
            messages.info(request,'Credentials given are wrong')
            return redirect('University:login')
    else:
        return render(request,'login.html')

def signUp(request):
    if request.method=='POST':
        fullname=request.POST['fullname']
        username=request.POST['id']
        email=request.POST['email']
        password=request.POST['password']
        confirmPassword=request.POST['confirmPassword']
        
        if password==confirmPassword:
            if User.objects.filter(email=email).exists():
                messages.info(request,'Email already used')
                return redirect('University:signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request,'ID already exists')
                return redirect('University:signup')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save();
                student=studentRegistration.StudentAdd(username,fullname,email)
                student.addStudent()
                return redirect('University:login')
                


        else:
            messages.info(request, 'Two passwords did not match')
            return redirect('University:signup')
    else:
         return render(request, 'sign_up.html')
     
@login_required
def menu(request):
    return render(request,"menu.html")

@login_required
def course_add(request):
    if request.method=='POST':
        id=request.POST['courseID']
        name=request.POST['courseName']
        description=request.POST['description']
        
        course=courseadd.CourseAdd(id,name,description)
        course.addCourse()
    return render(request, 'course_add.html')

@login_required
def course_drop(request):
    
    if request.method=='POST':
        id=request.POST['courseID']
        course=courseadd.CourseAdd(id)
        course.deleteCourse()
    
    return render(request,'course_drop.html')

@login_required
def course_registration(request):
    data = serializers.serialize("python",OfferedCourse.objects.all())
    context = {
        'data':data,
    }
    return render(request, 'course_registration.html', context)

@login_required
def personal_information(request):
    return render(request, 'personal_information.html')

@login_required
def results(request):
    grades = Grade.objects.filter(owner=request.user).order_by('date_added')
    context = {'grades':grades}
    return render(request, 'results.html',context)

@login_required
def student_registration(request):
    return render(request, 'student_registration.html')

UniversitySite/University/templates/courseList.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Courses</title>
</head>
<body>
    <div class="container">
        <h2>Add Courses</h2>
        <p>

        </p>
    </div>

</body>
</html>

UniversitySite/University/templates/course_add.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Course Add/Drop</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'course_add.css' %}">
  </head>
  <body>
    <section class = "course">
      <div class="content">
        <h2>Add Course</h2>
        <p>Please, select your desired courses.</p>
      </div>
        <div class="course_add_form">
          <form method="POST">
            {% csrf_token %}
            <div class="inputBox">
              <input type="text" name="courseID" required="required">
              <span>Course ID</span>
            </div>
            <div class="inputBox">
              <input type="text" name="courseName" required="required">
              <span>Course Name</span>
            </div>
            <div class="inputBox">
              <textarea required="required" name="description"></textarea>
              <span>Description</span>
            </div>
            <div class="inputBox">
              <input type="submit" name="" value="Submit">
            </div>
          </form>
        </div>
    </section>
  </body>
</html>

UniversitySite/University/templates/course_drop.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Course Add/Drop</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'course_drop.css' %}">
  </head>
  <body>
    <section class = "course">
      <div class="content">
        <h2>Drop Course</h2>
        <p>Please, select the courses you want to drop.</p>
      </div>
        <div class="course_drop_form">
          <form method="POST">
            {% csrf_token %}
            <div class="inputBox">
              <input type="text" name="courseID" required="required">
              <span>Course ID</span>
            </div>
            <div class="inputBox">
              <input type="submit" name="" value="Submit">
            </div>
          </form>
        </div>
    </section>
  </body>
</html>

UniversitySite/University/templates/course_registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Offered Courses</title>
    <link rel="stylesheet" href="{% static 'offered_courses.css' %}">
  </head>

  <!-- <script>
    let sortDirection = false;
    let courseData = [
      { id: 123, course_name: "CSE", course_description: "DataStructures" },
      { id: 123, course_name: "CSE", course_description: "DataStructures" },
      { id: 123, course_name: "CSE", course_description: "DataStructures" },
      { id: 123, course_name: "CSE", course_description: "DataStructures" },
      { id: 123, course_name: "CSE", course_description: "DataStructures" }
    ];

    window.onload = () => {
      loadTableData(courseData);
    };

    function loadTableData(courseData){
      const tableBody = document.getElementById("tableData");
      let dataHtml = '';

      for(let course of courseData){
        dataHtml += `<tr><td>${course.id}</td><td>${course.course_name}</td><td>${course.course_description}</td></tr>`;
      }
      console.log(dataHtml)

      tableBody.innerHTML = dataHtml;
    } -->

  </script>

  <body>
    <section class="container">
      <div class="content">
        <h2>Offered Courses</h2>
      </div>
      <div class="offered_courses_table">
        <table>
          <thead>
            <tr>
              <th>Course ID</th>
              <th>Course Name</th>
              <th>Course Description</th>
            </tr>
          </thead>
          {% for instance in data %}
          <tr>
            <td>
              {{ instance.fields.owner_id }}
            </td>
            <td>
              {{ instance.fields.name }}
            </td>
            <td>
              {{ instance.fields.description }}
            </td>
          </tr>
          {% endfor  %}
         </table>
      </div>
    </section>
  </body>
</html>

UniversitySite/University/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>RITU</title>
    <link rel="stylesheet" href="{% static 'homepage.css' %}">
  </head>
  <body>
    <div class="banner">
      <div class="navbar">

      </div>

    </div>

    <div class="content">
      <h1>University Database</h1>
      <p>The University Database of <br>BUET</p>
      <div>
        <a href="{% url 'University:login' %}">
        <button type="button"><span></span>LOGIN</button></a>
        <a href="{% url 'University:signup' %}">
        <button type="button"><span></span>SIGN UP</button></a>
      </div>
    </div>

  </body>
</html>

UniversitySite/University/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <title>Login Form | CodingLab</title> -->

    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
  </head>
  <body>
    <div class="container">
      <div class="wrapper">
        <div class="title"><span>Login</span></div>

        <form method="POST" action="login">
          {% csrf_token %}
          <div class="row">
            <i class="fas fa-user"></i>
            <input type="text" name="id" placeholder="User ID" required>
          </div>
          <div class="row">
            <i class="fas fa-lock"></i>
            <input type="password" name="password" placeholder="Password" required>
          </div>
          <div class="pass"><a href="#">Forgot password?</a></div>
          <div class="row button">
            <input type="submit" value="Login">
          </div>

          <div class="signup-link">Not a member? <a href="#">Signup now</a></div>
        </form>
      </div>
    </div>

  </body>
</html>

UniversitySite/University/templates/menu.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>UNIVERSITY</title>
  </head>
  <body>
    <h1>UNIVERSITY</h1>
    <div class="banner">
      <div class="navbar">
        <ul>
          <li><a href="{% url 'University:student_registration' %}">Student Registration</a></li>
          <li><a href="{% url 'University:course_registration' %}">Course Registration</a></li>
          <li><a href="{% url 'University:course_add' %}">Course Add</a></li>
          <li><a href="{% url 'University:course_drop' %}">Course Drop</a></li>
          <li><a href="{% url 'University:results' %}">Grades</a></li>
          <li><a href="{% url 'University:personal_information' %}">Personal Information</a></li>
        </ul>

      </div>
      </div>

  </body>
</html>

UniversitySite/University/templates/personal_information.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Your Information</h1>
  </body>
</html>

UniversitySite/University/templates/results.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Grades</title>
  </head>
  <body>
    <h1>Grades</h1>

    {% block content %}

    <ol>
      {% for grade in grades %}
        <li>{{ grade.course_id }} - {{ grade.result }}</li>
      {% empty %}
        <li>No grades have been released yet.</li>
      {% endfor %}
    </ol>

    {% endblock content %}

  </body>
</html>

UniversitySite/University/templates/sign_up.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create your Account</title>
    <link rel="stylesheet" href="{% static 'sign_up.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
</head>
<body>
    <div class="container">
        <div class="title">SignUp Form</div>

        <form method="POST" action="signup">
            {% csrf_token %}
            <div class="user-details">
                <div class="inputBox">
                    <span class="details">Full Name</span>
                    <input type="text" name="fullname" placeholder="Enter Your Full Name" required>
                </div>
                <div class="inputBox">
                    <span class="details">ID</span>
                    <input type="text" name="id" placeholder="Enter Your ID" required>
                </div>
                <div class="inputBox">
                    <span class="details">Email</span>
                    <input type="text" name="email" placeholder="Enter Your Email" required>
                </div>
                <div class="inputBox">
                    <span class="details">Password</span>
                    <input type="password" name="password" placeholder="Enter a strong password" required>
                </div>
                <div class="inputBox">
                    <span class="details">Confirm Password</span>
                    <input type="password" name="confirmPassword" placeholder="Confirm Password" required>
                </div>
            </div>
            <div class="button">
                <input type="submit" value="SignUp">
            </div>
        </form>
    </div>
</body>
</html>

UniversitySite/University/templates/student_registration.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Register</h1>
  </body>
</html>